In [1]:
import pandas as pd

In [2]:
data={"product":["laptop","phone","tablet","headphone","monitor","keyboard","mouse","laptop","phone","monitor"],
      "category":["electronics","electronics","electronics","accessories","electronics","accessories","accessories","electronics","electronics","electronics"],
      "sales":[75000,50000,30000,5000,25000,3000,1500,80000,55000,28000], "quantity":[3,5,4,10,6,15,20,4,6,7]}
df=pd.DataFrame(data)
df

     product     category  sales  quantity
0     laptop  electronics  75000         3
1      phone  electronics  50000         5
2     tablet  electronics  30000         4
3  headphone  accessories   5000        10
4    monitor  electronics  25000         6
5   keyboard  accessories   3000        15
6      mouse  accessories   1500        20
7     laptop  electronics  80000         4
8      phone  electronics  55000         6
9    monitor  electronics  28000         7

In [3]:
df.to_csv("cleaned_sales_data.csv",index=False)
print("dataset exported")

dataset exported

In [5]:
new_df=pd.read_csv("cleaned_sales_data.csv")
new_df

     product     category  sales  quantity
0     laptop  electronics  75000         3
1      phone  electronics  50000         5
2     tablet  electronics  30000         4
3  headphone  accessories   5000        10
4    monitor  electronics  25000         6
5   keyboard  accessories   3000        15
6      mouse  accessories   1500        20
7     laptop  electronics  80000         4
8      phone  electronics  55000         6
9    monitor  electronics  28000         7

In [6]:
print("no.of rows:",new_df.shape[0])
print("no.of columns:",new_df.shape[1])

no.of rows: 10
no.of columns: 4

In [7]:
print(new_df.info())

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   product   10 non-null     str
 1   category  10 non-null     str
 2   sales     10 non-null     int64
 3   quantity  10 non-null     int64
dtypes: int64(2), str(2)
memory usage: 626.0 bytes
None