In [8]:
import pandas as pd
table={"name":["rahul","asha","riya","vishnu","amal"],"age":["20","21","19","20","18"],"gender":["male","female","female","male","male"]}
df=pd.DataFrame(table)
print(df)

     name age  gender
0   rahul  20    male
1    asha  21  female
2    riya  19  female
3  vishnu  20    male
4    amal  18    male

In [9]:
df.head()
df.tail()

     name age  gender
0   rahul  20    male
1    asha  21  female
2    riya  19  female
3  vishnu  20    male
4    amal  18    male

In [10]:
print(df.columns)

Index(['name', 'age', 'gender'], dtype='str')

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      str
 1   age     5 non-null      str
 2   gender  5 non-null      str
dtypes: str(3)
memory usage: 309.0 bytes

In [12]:
df.describe()

         name age gender
count       5   5      5
unique      5   4      2
top     rahul  20   male
freq        1   2      3

In [13]:
print(df.shape)

(5, 3)

In [15]:
print(df["gender"])

0      male
1    female
2    female
3      male
4      male
Name: gender, dtype: str

In [17]:
print(df[["name","age","gender"]])

     name age  gender
0   rahul  20    male
1    asha  21  female
2    riya  19  female
3  vishnu  20    male
4    amal  18    male